#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'malicious'
require 'virustotal_api'
require 'awesome_print'
require 'dotenv'

Dotenv.load

api_key = ENV['VIRUS_TOTAL_API_KEY']
client = Malicious::VirusTotal::Client.new(api_key: api_key)

malicious_urls = [
  'https://thetowelfactory.com/new/login/index.php',
  'https://grosfeld.global/me/login/index.php',
  'https://gilsondaub.cf/index/newpage/index.php',
  'https://vatsparivar.com/Admin/login/index.php',
  'https://agilemsc.com/Acci/wp-includes/index.php',
  'https://liascatering.com/fax/login/index.php',
]

domain = malicious_urls.sample.split('/')[2]
url = malicious_urls.sample

result = client.domain_scan(domain)
p result.detected_urls.map(&:url)
p result.detected_urls.map(&:positives)
p result.positives
ap result.positives
ap result.vulnerable?

result = client.url_scan(url)

if result
  ap result
  ap result.ready?
  ap result.malicious?
  ap result.positives
  ap result.scan_date
  ap result.scans
else
  puts 'nothing found'
end
