#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'malicious'
require 'virustotal_api'
require 'awesome_print'
require 'dotenv'

Dotenv.load

api_key = ENV['VIRUS_TOTAL_API_KEY']
client = Malicious::VirusTotal::Client.new(api_key: api_key)

samples = Malicious::Samples.new

#-------------------------------------------------------------------------------
# Domain
#-------------------------------------------------------------------------------
domain = samples.domains.sample
puts '-' * 80
puts "Sample domain: #{domain}"
puts '-' * 80

result = client.domain_scan(domain)
p result.detected_urls.map(&:url)
p result.detected_urls.map(&:positives)
p result.positives
ap result.positives
ap result.vulnerable?

#-------------------------------------------------------------------------------
# Url
#-------------------------------------------------------------------------------
url = samples.urls.sample
puts '-' * 80
puts "Sample url: #{url}"
puts '-' * 80
result = client.url_scan(url)

if result
  ap result
  ap result.ready?
  ap result.malicious?
  ap result.positives
  ap result.scan_date
  ap result.scans
else
  puts 'nothing found'
end
